blueprint:
  name: Toggle RGB Colors for Selected Lamps
  description: A script to toggle RGB colors for selected lamps on each activation.
  domain: script
  input:
    lamp_entities:
      name: Lamp Entities
      description: Select the lamps to toggle colors
      selector:
        target:
          entity:
            domain: light
    colors:
      name: RGB Colors
      description: Add RGB colors to toggle through
      default:
        - [255, 0, 0]  # Red
        - [0, 255, 0]  # Green
        - [0, 0, 255]  # Blue
      selector:
        object:
          type: array
          item:
            type: array
            items:
              - type: integer
              - type: integer
              - type: integer

variables:
  color_list: !input colors

sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ state_attr(target, 'rgb_color') == color_list[-1] }}
        sequence:
          - service: light.turn_on
            target: !input lamp_entities
            data:
              rgb_color: "{{ color_list[0] }}"
              brightness: 200
      - conditions:
          - condition: template
            value_template: >
              {% for color in color_list[:-1] %}
                {% if state_attr(target, 'rgb_color') == color %}
                  {{ color_list[color_list.index(color) + 1] }}
                {% endif %}
              {% endfor %}
        sequence:
          - service: light.turn_on
            target: !input lamp_entities
            data_template:
              rgb_color: "{{ color }}"
              brightness: 200
